//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BYSerial.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BYSerial.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Modbusl_dll {
            get {
                object obj = ResourceManager.GetObject("Modbusl_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] Modsim_lpu {
            get {
                object obj = ResourceManager.GetObject("Modsim_lpu", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] modsim32_cfg {
            get {
                object obj = ResourceManager.GetObject("modsim32_cfg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ModSim32_cnt {
            get {
                object obj = ResourceManager.GetObject("ModSim32_cnt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ModSim32_exe {
            get {
                object obj = ResourceManager.GetObject("ModSim32_exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] MODSIM32_GID {
            get {
                object obj = ResourceManager.GetObject("MODSIM32_GID", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] MODSIM32_HLP {
            get {
                object obj = ResourceManager.GetObject("MODSIM32_HLP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 [Default]
        ///Device Number = 1
        ///Modbus Command = 3
        ///Address = 100
        ///Length = 100
        /// 的本地化字符串。
        /// </summary>
        internal static string ModSim32_ini {
            get {
                return ResourceManager.GetString("ModSim32_ini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ModSim32_tlb {
            get {
                object obj = ResourceManager.GetObject("ModSim32_tlb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 VERSION 4.00
        ///Begin VB.Form Form1 
        ///   Caption         =  &quot;Form1&quot;
        ///   ClientHeight    =  3555
        ///   ClientLeft      =  3195
        ///   ClientTop       =  2565
        ///   ClientWidth     =  5250
        ///   Height          =  3555
        ///   Left            =  3195
        ///   LinkTopic       =   &quot;Form1&quot;
        ///   ScaleHeight     =   3150
        ///   ScaleWidth      =   5130
        ///   Top             =  2565
        ///   Width           =  5250
        ///   Begin VB.TextBox Text2 
        ///      Height          =  285
        ///      Left            =  3360
        ///      TabIndex        =   3
        ///      Text    [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ModSimEx_frm {
            get {
                return ResourceManager.GetString("ModSimEx_frm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ModSimEx_vbp {
            get {
                object obj = ResourceManager.GetObject("ModSimEx_vbp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ModSimEx_vbw {
            get {
                object obj = ResourceManager.GetObject("ModSimEx_vbw", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] ms32comm_cfg {
            get {
                object obj = ResourceManager.GetObject("ms32comm_cfg", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
